### ISSUE TITLE
Unknown provider: evaProvider

### ISSUE THREAD

**Issue by Masterdanielsan** [uqee/angular-evaporate#10]
I keep getting this error when trying to add angular-evaporate to my project.  I followed the instructions exactly.
the following simply does not work:

app.config(['evaProvider', function(evaProvider) {
}]);

and gives the following error:
Error: $injector:unpr
Unknown Provider

**Comment by uqee** [comment]
Hi, @Masterdanielsan , looks like you've accidentally missed or mistyped either dependency declaration

```
angular.module('<your app name>', ['evaporate']);
```

or inclusion

```
<script src="/bower_components/angular-evaporate/lib/angular-evaporate.min.js"></script>
```

of the module. If that didn't help, please provide more details about the code you use.

**Comment by Masterdanielsan** [comment]
No. I confirmed that the angular-evaporate lib was included.

It appears that the v 1.x instructions just don't work.  I used the $scope.evaConfigInit method in the main controller instead... seems to not give errors on load now.

**Comment by uqee** [comment]
Oh, I got it. You followed instructions for the v1.x while actually using v2.0.0-alpha, which is the default now. I'll update a readme to make it more clear, thanks for your feedback!
