### ISSUE TITLE
Feature request: pre-validating files

### ISSUE THREAD

**Issue by tot-ra** [uqee/angular-evaporate#11]
Would be nice to have in settings callback function that would first check if uploading of file is nessesary.. here is an example (see **onFileDrop**)
https://github.com/tot-ra/angular-evaporate/blob/master/lib/angular-evaporate.js

The function should return a promise in case prevalidation is time consuming and requires network calls, alerts etc. And it should return filtered files

**Comment by uqee** [comment]
Thanks for the iddea, but I'm not sure if this functionality really fits the library or should better be done separately. Did you consider other options before forking the lib and with what results?

**Comment by Masterdanielsan** [comment]
I had a similar question.  Is there a way to delay the upload until the user selects all the files wanted, and maybe makes a call to the server telling it to do something and then press a single "go" button that does the actual upload?
