### ISSUE TITLE
input add files to a list instead of immediately uploading

### ISSUE THREAD

**Issue by Masterdanielsan** [uqee/angular-evaporate#15]
The functionality I need out of angular-evaporate is to trigger an upload all at once.

In order to do this, I need the browse input to not automatically go into an upload frenzy after files have been chosen.  Instead, I would like for these to be added to a list.  I would additionally like to add my own file (a json that lists all the files to be uploaded, so that the entire upload can be considered a package).  Once this is done, I would like the user to be able to hit "go" and then start the uploading process.

Is this something that I can accomplish with angular-evaporate?  Is there someone who could help me implement this behavior?

I would REALLY appreciate any help/direction.

**Comment by uqee** [comment]
Hi, @Masterdanielsan 
Do I understand correctly, that you want a custom `<input type="file" ...>` to generate a list of files, which will be uploaded later? Looks like we need an additional factory to add files, start uploading, etc. And all the UI will be separated and created on your own, right?

**Comment by Masterdanielsan** [comment]
Yeah, that sounds right.  I REALLY want to be able to use angular-evaporate for my project.  I would love to be able to have a conversation with you if possible.  I made my email public if you would be interested in having a conversation.  Maybe we could make some headway on this together?

**Comment by uqee** [comment]
We'll do. Just need to thoroughly think through all the desired features, to implement them within a consistent logic and not break any backward compatibility. I'll start a new branch, feel free to comment it at any time. What's your deadline for this task?

**Comment by uqee** [comment]
Or may be just directly expose Evaporate itself (via factory)? Add a little sugar of lazy configuration, etc. What do you think?

**Comment by Masterdanielsan** [comment]
Sorry, got pulled away for a day on another project. I'm trying to get this project completed within the next two weeks (the sooner the better).  I'd really love to chat in real-time if possible.  I'm only at an intermediate level when it comes to angular development.

if the browse input could add all the files to a list (which is also exposed to the controller) and we could call "startUpload()" on any one of those objects or all of those objects, that would provide the necessary functionality.  I would also like to be able to pause an upload for a particular file and un-pause it (currently there is only a cancel option i believe).

I have another requirement that some or all of the files (they will be jpgs and tiffs for the most part) be displayed as thumbnails.

Use Case: The user selects a directory of (mostly) pictures -> some or all of them are displayed as thumbnails to the side somewhere ->user possibly adds more files -> some or all of those are added to the thumbnail section -> user is satisfied with upload -> user hits "upload all" button -> uploads start firing off in succession -> user can pause specific files or cancel them as the upload goes on

It will also be necessary for me to send up a json file alongside the files that the user selects so that the server knows which items are in the "package" that the user means to send.

Ambitious, but I'd like to do it through this library if possible. o.o;;

**Comment by Masterdanielsan** [comment]
Maybe a custom directive (with an input) that adds selected files to a list that a factory maintains?  Then maybe the factory can expose some functions to return a list of files currently in the queue as well as functions to delete/add files to it.  Finally, the factory could expose a function to upload all files in its queue as well as one to selectively upload a single or subsection of the files.

**Comment by uqee** [comment]
Morning, @Masterdanielsan !
I'm here, no worries) I think, thumbnails and all the related stuff is a totally different story, you're gonna need a [FileReader API](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL) to achieve this. As I see the workflow: you get a callback fired with a list of newly selected files, for every file you execute the code, mentioned in the article, and show thumbnails and all the desired controls using `ng-repeat`.

In the meantime I'll update the current directive to provide:
1. Lazy configuring.
2. New config options:
   
   a. an option to start uploading as soon as files are selected (will be on by default to conform with previous versions);
   b. a callback which would fire if files were selected and the latter option is off.
3. A list of files:
   
   a. ability to add/remove a file,
   b. function to start uploading all of them at once.
4. Uploading functions for every file in the list:
   
   a. start,
   b. pause,
   c. resume,
   d. cancel.

I'll also expose the bare Evaporate constructor through a corresponding factory.
Looks good?

**Comment by Masterdanielsan** [comment]
Looks amazing.  I sent you an email if you would be able to contact me and maybe have a few words in real-time.  I really appreciate the help and I think this is going to make this project really useful and nifty! :)
