### ISSUE TITLE
pauseAll() non-recoverable

### ISSUE THREAD

**Issue by Masterdanielsan** [uqee/angular-evaporate#22]
It seems that sometimes pauseAll() is non recoverable.  The resume fails, and no more retries are made on the paused files.

**Comment by uqee** [comment]
Are you sure it's a current module's issue? Because `AngularEvaporate.$pauseAll(...)` just directly calls `Evaporate.pause(undefined, ...)`. Probably `Evaporate`'s bug then, I guess, isn't it?

**Comment by Masterdanielsan** [comment]
I believe that evaporate v1.5.7 fixed this issue:
https://github.com/TTLabs/EvaporateJS/commit/a70a3f8807a4d6b23b590c9a9c44befcc32107b7

I can no longer reproduce after the update. :)

**Comment by uqee** [comment]
Cool)
