### ISSUE TITLE
How to generate SignerUrl using golang  code 

### ISSUE THREAD

**Issue by AshwiniMetgudmath** [uqee/angular-evaporate#31]
Hi,

I am using evaporatejs code for large file multipart upload, but i am not getting how to generate and use SignerUrl.  client side i am using angularjs and server side I am using golang code. and what input has to be  given for generating SignerUrl method.

**Comment by uqee** [comment]
HI! I'm not really familiar with Go, so can only recommend to look at the `example/server.js` file. Only a few lines of JS code there, which you would be interested in.
