### ISSUE TITLE
Running demo setup is giving CORS error

### ISSUE THREAD

**Issue by AshwiniMetgudmath** [uqee/angular-evaporate#32]
Hi,

I cloned github demo code and tried running it, I have changed bucket name, access key and secrete key in code.  I could not run on port 8080 so I changed it to 3000 and tried running,  I could run but when I am trying to upload I am getting CORS error. The error message is given below

XMLHttpRequest cannot load https://s3.amazonaws.com/quicksharebucketfree/angular-evaporate/public-read/07%3A48%3A23--56.jpg?uploads. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

**Comment by uqee** [comment]
Hi, @AshwiniMetgudmath, looks like you forgot to configure your bucket. Please, follow the instructions provided by the EvaporateJS creators.

**Comment by AshwiniMetgudmath** [comment]
Hello,

Bucket configuration i have done, but still I am getting same error.

**Comment by uqee** [comment]
Here's the specific link: https://github.com/TTLabs/EvaporateJS#configuring-the-aws-s3-bucket
Are you sure your bucket CORS config looks similar to this:
```
<CORSConfiguration>
    <CORSRule>
        <AllowedOrigin>https://localhost:3000</AllowedOrigin>
        <AllowedOrigin>http://localhost:3000</AllowedOrigin>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>DELETE</AllowedMethod>
        <AllowedMethod>GET</AllowedMethod>
        <ExposeHeader>ETag</ExposeHeader>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```

**Comment by AshwiniMetgudmath** [comment]
Hello,

Along with  http://localhost:3000 i had added some other domains and * also, now i removed all and added only localhost:3000, It's working fine now. 

Thank you.
