### ISSUE TITLE
app.config provider object 

### ISSUE THREAD

**Issue by rosscdh** [uqee/angular-evaporate#6]
Hi there, great app.

It lacks however the config provider object so that one can define the settings in tehangular standard way and not via window.CONSTANT..

Is this possible?

**Comment by uqee** [comment]
Hi, @rosscdh, thanks for your feedback!
Yes, of course it's possible through the use of provider instead of factory. Would you do this yourself or do you want me to? PRs are always welcome)

**Comment by rosscdh** [comment]
I gave it a shot about 40 mins but there are some quirks and I gave up. I would really appreciate it

**Comment by rosscdh** [comment]
Fantastic! Thanks

**Comment by uqee** [comment]
You're welcome)
