### ISSUE TITLE
Uploading to two different buckets

### ISSUE THREAD

**Issue by peret** [uqee/angular-evaporate#9]
Is there an easy way to set up multiple evaporate-directives in the same application, so they upload to different S3-Buckets? E.g. I have a form with two evaporate-input elements and one of them should upload to 'my-images.s3.amazonaws.com', the other one to 'my-apps.s3.amazonaws.com'.

It seems to me that because the 'eva'-provider produces a singleton, all instances of the evaporate-directive share the same config and this can't currently be done. Is that correct?

I would gladly provide a pull request for this, but I'm not entirely sure what would be the best way to implement this..

**Comment by uqee** [comment]
You're right about the current implementation and your proposition also totally makes sense. Would it be ok if I have a look at it within a few days?

**Comment by peret** [comment]
Yes, that would be great, thank you! Let me know if I can help.

**Comment by uqee** [comment]
It should work, but I don't want to move it from the prerelease version without tests. Would be great to get your help in that direction if you please, because I'm afraid I don't have much time for that in the coming weeks.
